{% set name = "pys2index" %}
{% set version = "0.1.3" %}
{% set sha256 = "7a035204b99523338c8c978f6509192a02b4c04798646b5d53fad4709b20ee0d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/benbovy/pys2index/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv --ignore-installed --no-cache-dir

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]
  host:
    - python
    - xtensor-python >=0.26,<0.27
    - pybind11
    - pip
    - setuptools
    - numpy
    - s2geometry >0.10.0
  run:
    - python
    - s2geometry
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pys2index

about:
  home: https://github.com/benbovy/pys2index
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python/NumPy compatible geographical index based on s2geometry'

extra:
  recipe-maintainers:
    - benbovy
